# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Cates',
        ),
    ]
