# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20190716_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('goodsnum', models.IntegerField()),
                ('pic_url', models.CharField(max_length=255)),
                ('goodsinfo', models.TextField()),
                ('ordernum', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
        ),
    ]
