# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='cates',
            options={'permissions': (('show_Cates', '查看商品分类列表权限'), ('create_Cates', '添加商品分类权限'), ('edit_Cates', '修改商品分类信息权限'), ('delete_Cates', '删除商品分类权限'))},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_UGoods', '查看商品列表权限'), ('create_UGoods', '添加商品权限'), ('edit_UGoods', '修改商品信息权限'), ('delete_UGoods', '删除商品权限'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_Users', '查看会员列表权限'), ('create_Users', '添加会员权限'), ('edit_Users', '修改会员信息权限'), ('delete_Users', '删除会员权限'))},
        ),
        migrations.AddField(
            model_name='cart',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
    ]
