# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-22 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20190722_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cates',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
