# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_auto_20190722_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paytype',
            field=models.IntegerField(default=0),
        ),
    ]
